### ISSUE TITLE
Terminal backgrund settings

### ISSUE THREAD

**Issue by kseniamurex** [KeitaNakamura/neodark.vim#1]
Hi!
I'm using neodark with vim in the terminal, and I like it when my vim background is the same as the terminal background (I usually make it colored and transparent). So I added an option for it.
It can be enabled with `let g:neodark#terminal_transparent = 1`

Here the screenshot before:
![_2016-11-29_18-21-43](https://cloud.githubusercontent.com/assets/21336215/20715712/7a4bf80c-b669-11e6-803f-07733dc7c805.png)

And after:
![_2016-11-29_18-24-31](https://cloud.githubusercontent.com/assets/21336215/20715711/7a34ce8e-b669-11e6-845c-f77d9fccfed8.png)

I tried to make a pull request, but I'm very new to GitHub so I failed. So here is my patch. It'll be nice if you check it and (if you like the idea) push the code.
[0001-Added-terminal-background-settings.patch.txt](https://github.com/KeitaNakamura/neodark.vim/files/619377/0001-Added-terminal-background-settings.patch.txt)

**Comment by KeitaNakamura** [comment]
Thank you for using neodark!
I added a transparent background option with a different way, but didn't change color of ColorColumn as you suggested. Because if I change the color of ColorColumn, I also should change CursorLine, LineNr and so on. It's really hard... But I will try to find the way to solve this issue. Please give me a time.

**Comment by KeitaNakamura** [comment]
closed by #5
